//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Transports = new HashSet<Transport>();
        }
    
        public int PersonId { get; set; }
        public int PersonTypeId { get; set; }
        public string Surname { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int ExperienceWork { get; set; }
        public Nullable<int> TransportId { get; set; }
        public string Name { get; set; }
    
        public virtual PersonType PersonType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transport> Transports { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
