//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int RouteId { get; set; }
        public string FirstStop { get; set; }
        public string LastStop { get; set; }
    }
}
