//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transport()
        {
            this.Person = new HashSet<Person>();
        }
    
        public int TransportId { get; set; }
        public int RouteId { get; set; }
        public string EngineNumber { get; set; }
        public int FuelId { get; set; }
        public string Name { get; set; }
        public int TransportTypeId { get; set; }
    
        public virtual Fuel Fuel { get; set; }
        public virtual Route Route { get; set; }
        public virtual TransportType TransportType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Person { get; set; }
    }
}
