//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransportDBEntities : DbContext
    {
        public TransportDBEntities()
            : base("name=TransportDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Fuel> Fuel { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<PersonType> PersonType { get; set; }
        public virtual DbSet<TransportType> TransportType { get; set; }
        public virtual DbSet<Transport> Transport { get; set; }
    }
}
