//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public int TransportId { get; set; }
        public int RouteId { get; set; }
        public int PersonId { get; set; }
        public string EngineNumber { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual TransportType TransportType { get; set; }
    }
}
